theme: jekyll-theme-slate
title: Just-in-Time RE Workshop
description: A series of workshops on research into agile and just in time requirements elicitation, modeling, and use. <b>September 5, 2017, Lisbon, Portugal.<b>
